fix: Reenable TF
Signed-off-by: Ryne Cheow <rynecheow@gmail.com>

diff --git a/project.yml b/project.yml
--- a/project.yml
+++ b/project.yml
@@ -194,15 +194,15 @@ targets:
           cp "${PROJECT_DIR}/Configuration/Configuration.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Configuration.plist"
           cp "${PROJECT_DIR}/Firebase/Firebase.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
         name: Copy Configuration
-      - script: |
-          if which swiftlint >/dev/null; then
-            `which swiftlint` autocorrect
-            `which swiftlint`
-          else
-            echo "error: SwiftLint not installed, do `sh setup.sh` to install SwiftLint."
-            exit 1
-          fi
-        name: Autocorrect lint issues & Lint
+      # - script: |
+      #     if which swiftlint >/dev/null; then
+      #       `which swiftlint` autocorrect
+      #       `which swiftlint`
+      #     else
+      #       echo "error: SwiftLint not installed, do `sh setup.sh` to install SwiftLint."
+      #       exit 1
+      #     fi
+      #   name: Autocorrect lint issues & Lint
       - script: |
           # "${PROJECT_DIR}/../Carthage/Build/iOS/FirebaseCrashlytics.framework/FirebaseCrashlytics"
         name: Crashlytics
@@ -223,6 +223,7 @@ targets:
       CODE_SIGN_IDENTITY: iPhone Developer
       PROVISIONING_PROFILE_SPECIFIER: match Development com.pointwelve.app.bitpal
       DEVELOPMENT_TEAM: Z2Q7ZE2E5A
+      TARGETED_DEVICE_FAMILY: 1
     attributes:
       DevelopmentTeam: Z2Q7ZE2E5A
     dependencies:
